# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To create new specific image:
#   $ docker-compose build webgme (or any service name that needs to be rebuilt)
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# To stop containers:
#  $ docker-compose stop
version: '3'
networks:
  database:
    driver: bridge

services:
  mongo:
    image: mongo:3.4
    networks:
      - database
    # ports:
    # - 27017:27017 # Uncomment to expose mongo-port on host
    volumes:
      - ${BASE_DIR}/db:/data/db
  webgme:
    build:
      context: .
      dockerfile: webgme.Dockerfile
    networks:
      - database
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    ports:
      - 8888:8888
    volumes:
      - ${BASE_DIR}/src:/usr/app/src
  
